server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/serviceb
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true

management:
  endpoints:
    web.exposure.include: health,info

springdoc:
  swagger-ui.path: /swagger-ui.html

app:
  auth:
    static-token: ${APP_STATIC_TOKEN}